### ISSUE TITLE
Routes get created even though backend storage failed

### ISSUE THREAD

**Issue by holidaymike** [xmidt-org/ears#130]
To reproduce this issue, just configure ears with a none-existing dynamodb table. For example: 
```
  storage:
    route:
      type: dynamodb
      region: us-west-2
      tableName: badtable
```
Then create a route through the API. The API will fail with the following error:
```
{
    "status": {
        "code": 500,
        "message": "Internal Server Error"
    },
    "item": "InternalServerError: DynamoDbGetItemError: ResourceNotFoundException: Requested resource not found"
}
```
However, the route is still created. 

Also, the periodic global syncer can't seem to fix the issue. Instead, it will periodically show the following error log line:
```
{"log.level":"error","op":"StartGlobalSyncChecker","time":1623261548,"message":"DynamoDbGetItemError: ResourceNotFoundException: Requested resource not found"}
```
